# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MC02-Group9' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MC02-Group9
pod 'FSCalendar'
pod 'Gecco'
pod 'RxSwift'
pod 'RxCocoa'

pod 'Firebase/Firestore'
pod 'Firebase/Auth'
pod 'FirebaseFirestoreSwift'

pod 'Charts'
pod 'TinyConstraints'
pod 'Fastis'

end
